name: data-repo
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.4
  - pip
  - dash=1.9.1
  - dash-bootstrap-components=0.9.2
  - ipdb
  - ipykernel
  - numpy
  - pandas
  - scipy
  - plotly
  - pip:
    - dash_uploader