name: data-repo
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - dash=1.9.1
  - dash-bootstrap-components=0.9.2
  - ipdb=0.12.3
  - ipykernel=5.2.0
  - numpy=1.18.1
  - pandas=1.0.3
  - scipy=1.4.1
  - plotly=4.5.4